### ISSUE TITLE
Always show installed VS command prompts in File menu

### ISSUE THREAD

**Issue by chinarosesz** [spadapet/DevPrompt#31]
I have both Visual Studio 2017 and Visual Studio 2019 installed but DevPrompt only shows up Developer Command Prompt for 2017. It should automatically detect if I have this installed.

**Comment by spadapet** [comment]
Clicking "Reset" in the settings dialog will update the command prompts with the current versions of VS that are installed. But really the app should just show the proper VS command prompts without having to manually update.

The File menu could be:

- User specified command prompts
- Automatic VS prompts
- Automatic CMD and PowerShell prompts

**Comment by spadapet** [comment]
Commit 509bdcbd1d9386a4fe10bfd097ae0d59ba4743e8
You'll have to click "Reset" in the command prompt settings dialog one more time to remove the saved VS command prompts. The automatic VS prompts will be added into the File menu.
